
package it.polimi.bookstore.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerInfoImplService", targetNamespace = "http://ws.bookstore.polimi.it/", wsdlLocation = "http://localhost:8888/bookstorews/server?wsdl")
@HandlerChain(file="handler-chain.xml")
public class ServerInfoImplService
    extends Service
{

    private final static URL SERVERINFOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERINFOIMPLSERVICE_EXCEPTION;
    private final static QName SERVERINFOIMPLSERVICE_QNAME = new QName("http://ws.bookstore.polimi.it/", "ServerInfoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/bookstorews/server?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERINFOIMPLSERVICE_WSDL_LOCATION = url;
        SERVERINFOIMPLSERVICE_EXCEPTION = e;
    }

    public ServerInfoImplService() {
        super(__getWsdlLocation(), SERVERINFOIMPLSERVICE_QNAME);
    }

    public ServerInfoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERINFOIMPLSERVICE_QNAME, features);
    }

    public ServerInfoImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVERINFOIMPLSERVICE_QNAME);
    }

    public ServerInfoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERINFOIMPLSERVICE_QNAME, features);
    }

    public ServerInfoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerInfoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerInfoImpl
     */
    @WebEndpoint(name = "ServerInfoImplPort")
    public ServerInfoImpl getServerInfoImplPort() {
        return super.getPort(new QName("http://ws.bookstore.polimi.it/", "ServerInfoImplPort"), ServerInfoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerInfoImpl
     */
    @WebEndpoint(name = "ServerInfoImplPort")
    public ServerInfoImpl getServerInfoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.bookstore.polimi.it/", "ServerInfoImplPort"), ServerInfoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERINFOIMPLSERVICE_EXCEPTION!= null) {
            throw SERVERINFOIMPLSERVICE_EXCEPTION;
        }
        return SERVERINFOIMPLSERVICE_WSDL_LOCATION;
    }

}
